// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerConfig(arg1) {
  return window['go']['main']['App']['AddServerConfig'](arg1);
}

export function ApiTest(arg1) {
  return window['go']['main']['App']['ApiTest'](arg1);
}

export function CloseDBConnect(arg1) {
  return window['go']['main']['App']['CloseDBConnect'](arg1);
}

export function DeleteServerConfig(arg1) {
  return window['go']['main']['App']['DeleteServerConfig'](arg1);
}

export function EditServerConfig(arg1) {
  return window['go']['main']['App']['EditServerConfig'](arg1);
}

export function EditUserConfigItem(arg1) {
  return window['go']['main']['App']['EditUserConfigItem'](arg1);
}

export function GetServerConfig(arg1) {
  return window['go']['main']['App']['GetServerConfig'](arg1);
}

export function GetServerConfigList() {
  return window['go']['main']['App']['GetServerConfigList']();
}

export function GetUserConfig() {
  return window['go']['main']['App']['GetUserConfig']();
}

export function OpenDBConnect(arg1) {
  return window['go']['main']['App']['OpenDBConnect'](arg1);
}

export function QueryTableFieldList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryTableFieldList'](arg1, arg2, arg3, arg4);
}

export function QueryTableList(arg1, arg2) {
  return window['go']['main']['App']['QueryTableList'](arg1, arg2);
}

export function RefreshDBConnect(arg1) {
  return window['go']['main']['App']['RefreshDBConnect'](arg1);
}

export function ReturnError(arg1) {
  return window['go']['main']['App']['ReturnError'](arg1);
}

export function ReturnSuccess(arg1) {
  return window['go']['main']['App']['ReturnSuccess'](arg1);
}

export function TestDBConnect(arg1) {
  return window['go']['main']['App']['TestDBConnect'](arg1);
}
