// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetServerConfig():Promise<any>;

export function GetUserAppDataPath(arg1:string):Promise<string>;

export function SaveServerConfig(arg1:main.serverConfig):Promise<{[key: string]: any}>;
