// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetUserAppDataPath(arg1) {
  return window['go']['main']['App']['GetUserAppDataPath'](arg1);
}

export function SaveServerConfig(arg1) {
  return window['go']['main']['App']['SaveServerConfig'](arg1);
}
