// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerConfig(arg1) {
  return window['go']['main']['App']['AddServerConfig'](arg1);
}

export function DeleteServerConfig(arg1) {
  return window['go']['main']['App']['DeleteServerConfig'](arg1);
}

export function EditServerConfig(arg1) {
  return window['go']['main']['App']['EditServerConfig'](arg1);
}

export function GetServerConfig(arg1) {
  return window['go']['main']['App']['GetServerConfig'](arg1);
}

export function GetServerConfigList() {
  return window['go']['main']['App']['GetServerConfigList']();
}

export function GetUserAppDataPath(arg1) {
  return window['go']['main']['App']['GetUserAppDataPath'](arg1);
}

export function ReturnError(arg1) {
  return window['go']['main']['App']['ReturnError'](arg1);
}

export function ReturnSuccess(arg1) {
  return window['go']['main']['App']['ReturnSuccess'](arg1);
}

export function TestDBConnect(arg1) {
  return window['go']['main']['App']['TestDBConnect'](arg1);
}
